name: Deploy Content to Azure Sentinel
on: 
  push:
    branches: [ main ]
    paths:
    - 'Detections/**'
    - '.github/workflows/sentinel-deploy**'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'azure-sentinel-e2e-tip-wus2'
      workspaceName: 'azure-sentinel-e2e-tip-wus2'
      directory: '${{ github.workspace }}/Detections'
      cloudEnv: 'AzureCloud'
      creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_e0a988c76ede44709289b82acb71eeb4 }}

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_e0a988c76ede44709289b82acb71eeb4 }}
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v1

    - name: Read deployment script
      id: deploymentScript
      uses: juliangruber/read-file-action@v1
      with:
        path: '${{ github.workspace }}/.github/workflows\azure-sentinel-deploy.ps1'
    
    - name: Deploy Analytic Rules
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ steps.deploymentScript.outputs.content }}